### PR TITLE
[WIP] upgrade to support electron 4

### LINKED ISSUE #346: Electron 4 Support?
Is Electron 4 supported?  I after updating I seem to be having some issues.  I think `electron-chromedriver` needs to be updated to `4.0.0` but it's currently in beta and Spectron is pinned to `~3.0.0`.

### PR DESCRIPTION
**Pull request by shiftkey**
Fixes #346

### CODE REVIEW

**Comment by abaltzois** [comment]
Is there a planned date to merge?

**Comment by shiftkey** [comment]
> Is there a planned date to merge?

Not currently. I have to make time to see if I can even get the tests passing before we can talk about that.

**Comment by harryi3t** [comment]
@shiftkey Hey is there anything we can help you with this PR?

**Comment by shiftkey** [comment]
> Hey is there anything we can help you with this PR?

@harryi3t I honestly don't have the bandwidth to take this further, and I was hoping it would be as easy as bumping these dependencies but fixing the test failures and better understanding why they don't work now is something I'd love help with.

If those are minor things to fix, PRs into my fork would be welcome to verify they address this. If they're not, then 🤷‍♂...

**Comment by alexstrat** [comment]
@shiftkey I completed your PR here: https://github.com/electron/spectron/pull/361

**Comment by shiftkey** [comment]
Thanks @alexstrat. Closing this out in favour of #361

**Pull request closed without merging**
