### PR TITLE
improve AVA example

### PR DESCRIPTION
**Pull request by sindresorhus**
I'm a AVA maintainer.

-

// @jamestalmage

### CODE REVIEW

**Comment by jamestalmage** [comment]
I have got to imagine it requires the `--serial` flag, right? You wouldn't want multiple tests manipulating the browser at once.

Would be cool to figure out a way to launch multiple browsers, and distribute them to tests.

**Comment by sindresorhus** [comment]
@jamestalmage Seems like it spawns a new app instance of each tests: https://github.com/electron/spectron/pull/43/files#diff-04c6e90faac2675aa89e2176d2eec7d8R440

**Comment by jamestalmage** [comment]
Oh, if that's the case, it should technically work, but now I am concerned about system load.

If you have a hundred tests, it's going to try to launch a hundred app instances, right?

Unless maybe spectron is doing something clever under the hood with this promise [here](https://github.com/electron/spectron/pull/43/files#diff-04c6e90faac2675aa89e2176d2eec7d8R443), that restricts concurrency?

**Comment by kevinsawicki** [comment]
Awesome, thanks @sindresorhus

**Pull request merged**
